const config = {
  server: {
    path: "https://vvgnlisandboxapi.herokuapp.com/api/vvgnli/v1/",
    port: "",
  },
  api: {
    login: "login",
    signUp: "signup",
    uploadMedia: "upload",
    handlePost: "post/postHandle",
    getApprovedPhotos: "post/getApprovedPhotos",
    getPendingPhotos: "post/getPendingPhotos",
    updatePostStatus: "post/updatePostStatus",
    getPendingVideos: "post/getPendingVideos",
    getApprovedVideos: "post/getApprovedVideos",
    getCountOfApprovedPhotos: "post/getCountOfApprovedPhotos",
    getCountOfApprovedVideos: "post/getCountOfApprovedVideos",
    getPendingResearchWork: "post/getPendingResearchWork",
    getApprovedResearchWork: "post/getApprovedResearchWork",
    getUserDetails: "getUserDetails",
    getVideosForUserId: "post/getVideosForUserId",
    getPhotosForUserId: "post/getPhotosForUserId",
    getResearchWorkForUserId: "post/getResearchWorkForUserId",
    deletePost: "post/deletePost",
    changeUserRole: "changeUserRole",
    // getOtp: '/user/sendotp',
    // verifyOtp: '/user/verify?phoneNumber',
    forgotpassword: "forgot-password",
    uploadResearchWork: "uploadResearchWork",
    like: "post/like",
    comment: "post/comment",
    getCommentsOnPost: "post/getCommentsOnPost",
    getLikedPosts: "post/getLikedPosts",
    getFutureWebinars: "webinars/getFutureWebinars",
    getOngoingWebinars: "webinars/getOngoingWebinars",
    getPastWebinars: "webinars/getPastWebinars",
    updatePassword: "user/update-password",
    handlePostPic: "handleProfilePic",
    like: "like",
    comment: "comment",
    getCommentsOnPost: "getCommentsOnPost",
    getLikedPost: "getLikedPost",
    updateProfile: "updateProfile",
  },

  role: {
    admin: "admin/",
  },
};
export default config;
